### ISSUE TITLE
Error drawing chart before ajax call receives data

### ISSUE THREAD

**Issue by Sam-Davis** [bouil/angular-google-chart#158]
Perhaps there is an issue in the way I am getting my data, but, when I create a new chart object: 
$scope.myChartObject = {};
and then add the data from the server: 
$scope.myChartObject .data = <data from $http.get>
I sometimes get an error, when the chart draw function has been called before the data has been received. I have fixed this issue locally with the line change:
before:
if (!draw.triggered && ($scope.chart != undefined)) {
after:
if (!draw.triggered && ($scope.chart != undefined) && ($scope.chart.data != undefined)) {
or perhaps, this could be done more simply 
if (!draw.triggered && ($scope.chart != undefined)) {

**Comment by Balrog30** [comment]
The way I handle this in my project is to assign the entire chart object after the initial data loads.  If your chart is in the view for a route, you may consider using route resolves.  Resolves are loaded during route changes and the view is not rendered until all promises are resolved.  So your ajax call would be completed before rendering the view.  There's a simple example at this blog post: http://odetocode.com/blogs/scott/archive/2014/05/20/using-resolve-in-angularjs-routes.aspx

The disadvantage to route resolves is that your view isn't displayed until all promises are resolved, which can cause delays if your back-end is slow.  I've seen examples of directives that others have written to display a loading spinner or box of some kind until the route change has been completed.  I did a quick search, but couldn't find the one I had in mind for an example, but there are a few posted on jsfiddle, Stack Overflow and Plunker.

Personally, I like seeing an error when there's no data, because it helps me track down problems.  If I'm not creating the chart object until there is data, and I get that error, then I know there's something wrong in either the data I've received, or the way I'm handling it once I've got it.  Sometimes errors are a necessary evil, the trick is in structuring your web app so that it fails gracefully when it is actually being used.

Disclaimer: Everything above is only my opinion.  I welcome the opportunity to be set straight if others disagree.

**Comment by Sam-Davis** [comment]
Ah yes, that is a better way of doing it.

**Comment by Sam-Davis** [comment]
Thanks
