### ISSUE TITLE
Changing chart type can invalidate axis labels.

### ISSUE THREAD

**Issue by jthope** [bouil/angular-google-chart#164]
http://bouil.github.io/angular-google-chart/#/fat

1. Change chart type to BarChart
2. Date and Sales Unit labels do not get swapped

I am curious to see if anyone has a clean approach for fixing this. Currently, I am just swapping the labels when the chart type is changed to BarChart. Wondering if this logic could benefit by being added to angular-google-chart or if it should be kept independent from the library.

**Comment by Balrog30** [comment]
There was once a pull request (#118) that was proposed to resolve this issue.

### My thoughts on this issue
- We should definitely fix the demo page.
- Building this into the directive is contrary behaviour to the Google Charts API.
- Existing users have probably already written work-arounds themselves, so adding one directly to the directive would be a breaking change.

All that being said, I think it should be considered, especially since it's come up more than once... but if added the version number should change to reflect the breaking changes to as not to break people without warning for those using package managers with auto-updates.

**Comment by jthope** [comment]
Hey Balrog, I agree with your thoughts on this. I was able to fix the issue in the application I am working on, however, the fix is more custom to the application behavior and would not be a good fit for this directive.

I am going to close this issue as it sounds more like a feature request. Creating an option for swapping axis when the chart type is changed could be set as an optional configuration value -- which should eliminate any breaking changes. I'll take a look and see if I can come up with something clean.
