### ISSUE TITLE
Gauge chart click event

### ISSUE THREAD

**Issue by zszep** [bouil/angular-google-chart#165]
Currently I am displaying a gauge chart with 12 items for each month. Is it possible to determine which month was clicked on. I need this to be able to display detail data for the clicked month.

**Comment by Balrog30** [comment]
I don't have a complete answer for you, but I wanted to get back to you in a timely manner with somewhere to get started.

I have never attempted to use click events with a gauge chart, but I'll walk you through what I would take as my first steps if I had a project with a set of working gauge charts already in it.

First, add the `on-select` attribute to your chart element.

```HTML
<div chart="myChart" on-select="gaugeClicked(selectedItem)"></div>
```

Then, add your click handler to you controller.

```JavaScript
// Untested code, use as a guideline only.

(function(){
  angular.module('myApp')
    .controller('MainController', MainController);

  MainController.$inject = ['$scope', '$log'];
  
  function MainController($scope, $log){
    $scope.myChart = {
      // setup your chart
    };

    $scope.gaugeClicked = function(selectedItem){
      $log.debug('A gauge was clicked.  Here's the selectedItem:', selectedItem);
    };
  }
})();
```

I would set up something like the above, logging the `selectedItem` object to console so that I could then inspect them item to see the result.  I'm pretty sure it will give you a row and column for your selection, which you can then compare to your data set to figure out which gauge was clicked.  But then again maybe there is no select event for gauges... I honestly have not looked into this.

**Comment by zszep** [comment]
Sorry to inform you that this does not seem to work with gauge widgets. The gaugeClicked event is never being fired, so nothing is being logged to the console. I have seen a similiar answer to my problem on another chart type which does work, but the gauge control seems to be a different beast.

**Comment by Balrog30** [comment]
This probably means that the event is not implemented in the Google Chart API.  There's nothing we can do about that.  I would suggest creating a separate chart object for each dataset and putting an ng-click directive on each to do what you need to do.

To make your code a little cleaner you could store all the charts as an object with the month name as the key and a chart object as the value and then use ng-repeat with the key, value notation to display all the charts.

**Comment by zszep** [comment]
Your workaround with creating separate datasets is a reasonable alternative to solving the problem. Thanks.
