### ISSUE TITLE
Upgrade to Angular version 1.3.15

### ISSUE THREAD

**Issue by sojharo** [bouil/angular-google-chart#170]
I am trying to install this module to my application which uses angular 1.3.15. There are many modules which require angular version 1.3.15 in my application. However, when I install this module using bower, it wants me to have angularjs 1.2.28.

Can you please upgrade to angularjs version 1.3.15?

**Comment by Balrog30** [comment]
Are you aware that you can have bower save your conflict resolutions for angular version numbers so that it will not ask you again?  It will add a section to your project's bower.json to store your choice of version.

I think we are best to set the version to something like >1.2.x, since there are probably a number of users on Angular 1.2 that would have the same package manager annoyance that 1.3 users have now.

Also, I think the bulk of development was done in 1.2, with no changes required to work with 1.3, so it would be strange to set the angular dependency to 1.3.15.

**Comment by sojharo** [comment]
Kindly, let me know how can we do this. I just visited the bower website but could not find the way I can avoid bower asking me the version number on conflict. It asked me and I stopped the process because I didn't want to make choice.

I am worried about this as it will ask for this on CI server when CI server would install angular dependencies.

**Comment by Balrog30** [comment]
Here's a small piece of my project's bower.json...

```JavaScript
"dependencies": {
    "angular": "~1.3.15",
    "angular-google-chart": "~0.0.11"
},
"resolutions": {
    "angular": "~1.3.15"
}
```

This is what bower adds when you tell it to save your choice.

**Comment by sojharo** [comment]
This does not ask now, but gave the warning of code incompatibilities may occur. I am assuming that this would work and would test later. Closing this issue now.
